### ISSUE TITLE
Default Icinga rules should be documented

### ISSUE THREAD

**Issue by onitake** [unprofession-al/bpmon#1]
https://github.com/unprofession-al/bpmon/blob/master/icinga/icinga.go#L59 has default rules for handling Icinga conditions. These should be documented in the README, or moved to the examples.

Of particular importance is the "fallback" rule 9999 - if someone uses a higher number than 9999, unexpected behaviour may occur. This should be mentioned.

**Comment by gildegoma** [comment]
Adding a valid link to current implementation of icinga default rules: 
https://github.com/unprofession-al/bpmon/blob/89094366ea96aa92b86e16f3b15d2fa1c8f7d6c6/checker/icinga/icinga.go#L54-L79

It would also be worth giving an example where default rules are [merged](https://yaml.org/type/merge.html) or overridden. Something like the example bellow puzzled me:  

```yaml
my-section:
  <<: *default
  rules:
    25:
      must: [ critical, acknowledged ]
      then: ok
```
